site_name: yyc-library-review
nav:
  - Home: index.md
theme:
  name: material
  favicon: https://cdn3.iconfinder.com/data/icons/back-to-schools/120/Books_2-512.png
  logo: https://cdn3.iconfinder.com/data/icons/back-to-schools/120/Books_2-512.png
  font:
    text: Roboto
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.top
    - navigation.footer
plugins:
  - search
  - tags
  - glightbox:
      auto_caption: true
  - minify:
      minify_html: true
  - neoteroi.contribs:
      contributors:
        - email: imzehengl@gmail.com
          image: https://avatars.githubusercontent.com/u/6238966?v=4
markdown_extensions:
  - attr_list
  - md_in_html
repo_name: yyc-library-review
repo_url: https://github.com/zehengl/yyc-library-review
extra_css:
  - css/neoteroi-mkdocs.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zehengl
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/zehengl
