site_name: yyc-library-review
nav:
  - Home: index.md
theme:
  name: material
  favicon: https://cdn3.iconfinder.com/data/icons/education-and-school-8/48/Book-512.png
  logo: https://cdn3.iconfinder.com/data/icons/education-and-school-8/48/Book-512.png
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.top
    - navigation.footer
plugins:
  - search
  - tags
  - glightbox:
      auto_caption: true
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
markdown_extensions:
  - attr_list
  - md_in_html
